

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - GIN_MODE=debug
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - rating-service

  rating-service:
    build:
      context: .
      dockerfile: rating-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - GIN_MODE=debug
    volumes:
      - ./rating-service:/app


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"