version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ../Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["./main"]

  frontend:
    build:
      context: .
      dockerfile: ../Dockerfile.frontend
    ports:
      - "5173:80"
    volumes:
      - .:/app
    working_dir: /app
